DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS costs CASCADE;
DROP TABLE IF EXISTS tours CASCADE;

DROP FUNCTION IF EXISTS take_cost(INT, INT) CASCADE;
DROP PROCEDURE IF EXISTS tour_search(TEXT, INT, INT, INT) CASCADE;

